framework:
  - all

skip-check:
  - CKV_DOCKER_10
  - CKV_DOCKER_11
  - CKV_DOCKER_2
  - CKV_DOCKER_3
  - CKV_DOCKER_5
  - CKV_DOCKER_7
  - CKV_DOCKER_9
  - CKV_K8S_100
  - CKV_K8S_102
  - CKV_K8S_104
  - CKV_K8S_105
  - CKV_K8S_106
  - CKV_K8S_107
  - CKV_K8S_108
  - CKV_K8S_10
  - CKV_K8S_110
  - CKV_K8S_111
  - CKV_K8S_112
  - CKV_K8S_113
  - CKV_K8S_114
  - CKV_K8S_115
  - CKV_K8S_116
  - CKV_K8S_117
  - CKV_K8S_118
  - CKV_K8S_119
  - CKV_K8S_11
  - CKV_K8S_12
  - CKV_K8S_138
  - CKV_K8S_139
  - CKV_K8S_13
  - CKV_K8S_141
  - CKV_K8S_143
  - CKV_K8S_144
  - CKV_K8S_145
  - CKV_K8S_146
  - CKV_K8S_147
  - CKV_K8S_148
  - CKV_K8S_149
  - CKV_K8S_14
  - CKV_K8S_151
  - CKV_K8S_159
  - CKV_K8S_15
  - CKV_K8S_16
  - CKV_K8S_17
  - CKV_K8S_18
  - CKV_K8S_19
  - CKV_K8S_20
  - CKV_K8S_21
  - CKV_K8S_22
  - CKV_K8S_23
  - CKV_K8S_25
  - CKV_K8S_26
  - CKV_K8S_27
  - CKV_K8S_28
  - CKV_K8S_29
  - CKV_K8S_30
  - CKV_K8S_31
  - CKV_K8S_33
  - CKV_K8S_34
  - CKV_K8S_35
  - CKV_K8S_37
  - CKV_K8S_38
  - CKV_K8S_39
  - CKV_K8S_40
  - CKV_K8S_43
  - CKV_K8S_68
  - CKV_K8S_69
  - CKV_K8S_70
  - CKV_K8S_71
  - CKV_K8S_72
  - CKV_K8S_73
  - CKV_K8S_74
  - CKV_K8S_75
  - CKV_K8S_77
  - CKV_K8S_79
  - CKV_K8S_80
  - CKV_K8S_81
  - CKV_K8S_82
  - CKV_K8S_83
  - CKV_K8S_84
  - CKV_K8S_85
  - CKV_K8S_86
  - CKV_K8S_88
  - CKV_K8S_89
  - CKV_K8S_8
  - CKV_K8S_90
  - CKV_K8S_91
  - CKV_K8S_92
  - CKV_K8S_93
  - CKV_K8S_94
  - CKV_K8S_95
  - CKV_K8S_96
  - CKV_K8S_97
  - CKV_K8S_99
  - CKV_K8S_9

soft-fail: true
