repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
-   repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.334'
    hooks:
      - id: checkov
        verbose: true
        args: [
          --compact,
          --download-external-modules,"true",
          --quiet,
          --soft-fail,
          --skip-check, "",
          --soft-fail-on, "",
        ]
