apiVersion: apps/v1
kind: Deployment
metadata:
  name: chroma-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      containers:
      - name: chroma
        image: chroma-image:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: chroma-service
spec:
  selector:
    app: chroma
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
