apiVersion: apps/v1
kind: Deployment
metadata:
  name: openllm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openllm
  template:
    metadata:
      labels:
        app: openllm
    spec:
      nodeSelector:
        tier: openllm
      containers:
      - name: openllm
        image: docker.io/library/openllm-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: openllm-service
spec:
  selector:
    app: openllm
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30300
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: openllm-service-lb
spec:
  selector:
    app: openllm
  ports:
  - protocol: TCP
    port: 3010
    targetPort: 3000
    nodePort: 30310
  type: LoadBalancer
