kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30300
    hostPort: 3000
  labels:
    tier: openllm
- role: worker
  extraPortMappings:
  - containerPort: 30800
    hostPort: 8000
  labels:
    tier: chroma
